# Generated by Django 4.2.25 on 2025-10-24 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voguevue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=120)),
                ('region', models.CharField(blank=True, max_length=120, null=True)),
                ('country', models.CharField(max_length=80)),
                ('category', models.CharField(blank=True, max_length=80, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('annual_tourists', models.CharField(blank=True, max_length=80, null=True)),
                ('currency', models.CharField(blank=True, max_length=50, null=True)),
                ('majority_religion', models.CharField(blank=True, max_length=100, null=True)),
                ('famous_foods', models.CharField(blank=True, max_length=250, null=True)),
                ('language', models.CharField(blank=True, max_length=80, null=True)),
                ('best_time', models.CharField(blank=True, max_length=120, null=True)),
                ('cost_of_living', models.CharField(blank=True, max_length=80, null=True)),
                ('safety', models.CharField(blank=True, max_length=250, null=True)),
                ('cultural_significance', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
