# Generated by Django 5.2.7 on 2025-11-02 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voguevue', '0002_avis'),
    ]

    operations = [
        migrations.AddField(
            model_name='avis',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
