# Generated by Django 4.2.25 on 2025-10-23 11:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('voguevue', '0002_activity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['-created_at'], 'verbose_name': 'Activité', 'verbose_name_plural': 'Activités'},
        ),
        migrations.AddField(
            model_name='activity',
            name='profile',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Profil cible'),
        ),
        migrations.AddField(
            model_name='activity',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Dernière modification'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_name',
            field=models.CharField(max_length=255, verbose_name="Nom de l'activité"),
        ),
        migrations.AlterField(
            model_name='activity',
            name='category',
            field=models.CharField(max_length=100, verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='duration',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Durée'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='location',
            field=models.CharField(max_length=200, verbose_name='Ville'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='popularity',
            field=models.IntegerField(default=50, verbose_name='Popularité (0-100)'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='price',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Prix'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='weather',
            field=models.CharField(choices=[('sunny', 'Ensoleillé'), ('rainy', 'Pluvieux'), ('cloudy', 'Nuageux'), ('hot', 'Chaud'), ('cold', 'Froid'), ('snowy', 'Neigeux'), ('windy', 'Venteux')], max_length=50, verbose_name='Météo idéale'),
        ),
        migrations.AlterModelTable(
            name='activity',
            table='activities',
        ),
    ]
