# Generated by Django 4.2.25 on 2025-10-17 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voguevue', '0003_activity_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_table',
            name='city',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
