# Generated by Django 4.2.25 on 2025-11-02 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voguevue', '0003_alter_activity_options_activity_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='image_url',
            field=models.URLField(blank=True, null=True, verbose_name='Image IA générée'),
        ),
    ]
