# Generated by Django 4.2.25 on 2025-11-02 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('voguevue', '0004_activity_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, verbose_name='ID Session')),
                ('city', models.CharField(max_length=200, verbose_name='Ville')),
                ('user_message', models.TextField(verbose_name='Message utilisateur')),
                ('ai_response', models.TextField(verbose_name='Réponse IA')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Historique Chat',
                'verbose_name_plural': 'Historiques Chat',
                'db_table': 'chat_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='ai_generated',
            field=models.BooleanField(default=False, verbose_name='Contenu généré par IA'),
        ),
        migrations.AddField(
            model_name='activity',
            name='audio_description',
            field=models.TextField(blank=True, null=True, verbose_name='Audio IA (Base64)'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='image_url',
            field=models.TextField(blank=True, null=True, verbose_name='Image IA (Base64)'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['location'], name='activities_locatio_f7d96d_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['category'], name='activities_categor_1d724e_idx'),
        ),
        migrations.AddField(
            model_name='chathistory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
